name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust if your main branch is named differently

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          corepack enable
          yarn install

      - name: Build project
        run: yarn build

      - name: Add CNAME file
        run: echo "swis.sh" > .output/public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
          keep_files: true
